<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit12687503221f30495be14c7d47a58c58
{
    public static $files = array (
        '6632f90381dd49c5fe745d09406b9abb' => __DIR__ . '/..' . '/htmlburger/carbon-field-number/field.php',
    );

    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'Vardaam\\FilterAnything\\' => 23,
        ),
        'P' => 
        array (
            'PostTypes\\' => 10,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
            'Carbon_Fields_Plugin\\' => 21,
            'Carbon_Fields\\' => 14,
            'Carbon_Field_Number\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Vardaam\\FilterAnything\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'PostTypes\\' => 
        array (
            0 => __DIR__ . '/..' . '/jjgrainger/posttypes/src',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
        'Carbon_Fields_Plugin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/wp-content/plugins/carbon-fields-plugin/core',
        ),
        'Carbon_Fields\\' => 
        array (
            0 => __DIR__ . '/..' . '/htmlburger/carbon-fields/core',
        ),
        'Carbon_Field_Number\\' => 
        array (
            0 => __DIR__ . '/..' . '/htmlburger/carbon-field-number/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit12687503221f30495be14c7d47a58c58::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit12687503221f30495be14c7d47a58c58::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit12687503221f30495be14c7d47a58c58::$classMap;

        }, null, ClassLoader::class);
    }
}
