<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Vardaam\\FilterAnything\\' => array($baseDir . '/src'),
    'PostTypes\\' => array($vendorDir . '/jjgrainger/posttypes/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'Carbon_Fields_Plugin\\' => array($baseDir . '/wp-content/plugins/carbon-fields-plugin/core'),
    'Carbon_Fields\\' => array($vendorDir . '/htmlburger/carbon-fields/core'),
    'Carbon_Field_Number\\' => array($vendorDir . '/htmlburger/carbon-field-number/core'),
);
