<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '193dbad5ac0a4cda4ce1c6ebf64b5bd321b14bc0',
        'name' => 'vardaam/wp-filter-anything',
        'dev' => true,
    ),
    'versions' => array(
        'composer/installers' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'reference' => 'd20a64ed3c94748397ff5973488761b22f6d3f19',
            'dev_requirement' => false,
        ),
        'htmlburger/carbon-field-number' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../htmlburger/carbon-field-number',
            'aliases' => array(),
            'reference' => '3bddfaf256472d6071c62e566d011e1f2cdae0c6',
            'dev_requirement' => false,
        ),
        'htmlburger/carbon-fields' => array(
            'pretty_version' => 'v3.3.4',
            'version' => '3.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../htmlburger/carbon-fields',
            'aliases' => array(),
            'reference' => '2ae6773c004b873a1b0456613b14852c1a436a96',
            'dev_requirement' => false,
        ),
        'htmlburger/carbon-fields-plugin' => array(
            'pretty_version' => 'v3.3.4',
            'version' => '3.3.4.0',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../wp-content/plugins/carbon-fields-plugin',
            'aliases' => array(),
            'reference' => 'bdf850a5a321cd4187a5a1708aa70b5f2fb2523c',
            'dev_requirement' => false,
        ),
        'jjgrainger/posttypes' => array(
            'pretty_version' => 'v2.2',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jjgrainger/posttypes',
            'aliases' => array(),
            'reference' => '20f5a203316783a71ddfcd047ffebf1dc2bacb51',
            'dev_requirement' => false,
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'shama/baton' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'vardaam/wp-filter-anything' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '193dbad5ac0a4cda4ce1c6ebf64b5bd321b14bc0',
            'dev_requirement' => false,
        ),
    ),
);
